language: python
python:
  - "2.7"
  - "3.7"
dist: xenial
sudo: true
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -s C:\Users\Terrance\PycharmProjects\offline_dnd_utility\tests\unit